# name: Deploy to Azure Container App

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Log in to Azure
#         uses: azure/login@v2
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}

#       - name: Build and push Docker image
#         uses: azure/docker-login@v2
#         with:
#           login-server: telegramacr.azurecr.io
#           username: ${{ secrets.REGISTRY_USERNAME }}
#           password: ${{ secrets.REGISTRY_PASSWORD }}

#       - name: Build and push
#         run: |
#           docker build -t telegramacr.azurecr.io/telegram-listener:${{ github.sha }} .
#           docker push telegramacr.azurecr.io/telegram-listener:${{ github.sha }}

#       - name: Deploy to Azure Container App
#         run: |
#           az containerapp update --name telegram-listener --resource-group rg-hfinvest-prod \
#             --image telegramacr.azurecr.io/telegram-listener:${{ github.sha }}